// AUTO-GENERATED by tools/gen-assets.mjs — do not edit by hand.
export const TIME_DIGIT = { w: 80, h: 112 }
export const TIME_DIGITS = ["images/time/w0.png","images/time/w1.png","images/time/w2.png","images/time/w3.png","images/time/w4.png","images/time/w5.png","images/time/w6.png","images/time/w7.png","images/time/w8.png","images/time/w9.png"]
export const COLON = { w: 32, h: 112, src: 'images/colon.png' }

export const NUMSM = { w: 25, h: 35 }
export const NUMSM_WHITE = ["images/num/w0.png","images/num/w1.png","images/num/w2.png","images/num/w3.png","images/num/w4.png","images/num/w5.png","images/num/w6.png","images/num/w7.png","images/num/w8.png","images/num/w9.png"]
export const NUMSM_MINUS = 'images/num/minus.png'
export const DEGREE = { src: 'images/num/deg.png', w: 20, h: 28 }

export const NUMXS = { w: 20, h: 28 }
export const NUMXS_WHITE = ["images/numxs/w0.png","images/numxs/w1.png","images/numxs/w2.png","images/numxs/w3.png","images/numxs/w4.png","images/numxs/w5.png","images/numxs/w6.png","images/numxs/w7.png","images/numxs/w8.png","images/numxs/w9.png"]
export const NUMXS_RED = ["images/numxs/r0.png","images/numxs/r1.png","images/numxs/r2.png","images/numxs/r3.png","images/numxs/r4.png","images/numxs/r5.png","images/numxs/r6.png","images/numxs/r7.png","images/numxs/r8.png","images/numxs/r9.png"]

export const WORD = { w: 102, h: 42 }
export const WEEKDAY = ["images/word/wd0.png","images/word/wd1.png","images/word/wd2.png","images/word/wd3.png","images/word/wd4.png","images/word/wd5.png","images/word/wd6.png"]

export const NUMWD = { w: 30, h: 42 }
export const NUMWD_WHITE = ["images/numwd/w0.png","images/numwd/w1.png","images/numwd/w2.png","images/numwd/w3.png","images/numwd/w4.png","images/numwd/w5.png","images/numwd/w6.png","images/numwd/w7.png","images/numwd/w8.png","images/numwd/w9.png"]

export const WX_ICON = { w: 44, h: 44 }
export const WX = {
  "clear": "images/wx/clear.png",
  "partly": "images/wx/partly.png",
  "cloudy": "images/wx/cloudy.png",
  "overcast": "images/wx/overcast.png",
  "rain": "images/wx/rain.png",
  "snow": "images/wx/snow.png",
  "thunder": "images/wx/thunder.png",
  "fog": "images/wx/fog.png",
  "wind": "images/wx/wind.png"
}

export const ICON = { w9: 36 }
export const ICON_SRC = {
  "heart": "images/icon/heart.png",
  "heartSm": "images/icon/heart_sm.png",
  "spiral": "images/icon/spiral.png"
}
export const PREVIEW = 'images/preview.png'
